### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by gushmazuko** [chechen-language/keyboards#5]
## Missing symbols
There are missing symbols on desktop (global) layout:
- `:` [Unicode](https://www.compart.com/en/unicode/U+003A)
- `"` [Unicode](https://www.compart.com/en/unicode/U+0022)

## Bug
This is superfluous here in `On-Screen` keyboard, in the layout there are no characters under these buttons with `AltGr` and `Shift` pressed. @khashashin 
![Screenshot_4](https://user-images.githubusercontent.com/34921843/180660912-9813ab6e-e279-4a6e-b4bd-ae8c36ed0973.png)

But these symbols are in `AltGr` layer.
![Screenshot_5](https://user-images.githubusercontent.com/34921843/180661029-55104aea-b3ba-4066-a712-7c982de655e0.png)
![Screenshot_6](https://user-images.githubusercontent.com/34921843/180661032-469cfbc1-41aa-496d-92f2-540bf7d07903.png)

Extra lines (to be deleted):
- [L26](https://github.com/chechen-language/keyboards/blob/chechen_latin/experimental/c/chechen_latin/source/chechen_latin.kvks#L26)
- [L27](https://github.com/chechen-language/keyboards/blob/chechen_latin/experimental/c/chechen_latin/source/chechen_latin.kvks#L27)

**Comment by khashashin** [comment]
https://github.com/chechen-language/keyboards/pull/6
